export const colors = {
  backgroundPrimary: '#FFFFFF',
  backgroundSecondary: '#F8F8F8',
  backgroundTertiary: '#EDEDED',
  backgroundPrimaryInverse: '#000000',
  textPrimary: '#000000',
  textPrimaryInverse: '#FFFFFF',
  textSecondary: '#878787',
  borderStrong: '#9c9c9c',
  textLink: '#0066FF',
  tagGreen: '#EAFAD5',
  tagBlue: '#D0F0FF',
  tagRed: '#FFEAF1',
  tagSkyBlueActive: '#2abbff',
  tagMagentaActive: '#fb44fb',
  tagCyanActive: '#37d6d6',
  error: '#FFEAF1',
  oceanBlue: '#0066FF',
  darkOceanBlue: '#005DE8',
  brightRed: '#ce2c2c',
};
